# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170416_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 15, 10, 2, 459000, tzinfo=utc)),
        ),
    ]
