# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170416_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 3, 43, 20, 446000, tzinfo=utc)),
        ),
    ]
